[package]
name = "pth-render-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { version = "0.12", features = ["spirv"] }

[lib]
crate-type = ["dylib"]