[package]
name = "pooltouhou"
version = "0.1.0"
authors = ["euOnmyoji <1418780411@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
log = "0.4.14"
wgpu = "0.9.0"
wgpu_glyph = "0.13"
winit = "0.24"
pollster = "0.2.3"
futures = {version = "*", features = ["thread-pool"]}
image = "*"
rayon = "*"
lazy_static = "1.4.0"
glsl-layout = "0.3.2"
bytemuck = "*"
alto = "3.0.4"
rodio = "0.11.0"
shaderc = "0.7"

# https://amethyst.rs/doc

[features]
debug-game = []

shader-compiler = ["shaderc/build-from-source"]