[package]
name = "pooltouhou"
version = "0.1.0"
authors = ["euOnmyoji <1418780411@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
amethyst = "0.15.3"
nalgebra = "0.19.0"
lazy_static = "1.4.0"
glsl-layout = "0.3.2"
failure = "0.1.8"
derivative = "2.1.1"
amethyst_rendy = "0.15.3"
alto = "3.0.4"
rodio = "0.11.0"

# https://amethyst.rs/doc

[features]
default = ["vulkan", "shader-compiler"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]

shader-compiler = ["amethyst/shader-compiler"]
no-slow-safety-checks = ["amethyst/no-slow-safety-checks"]
