[package]
name = "pool_script_compiler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pool_script = { path = "../pool_script" }
log = "*"
env_logger = "*"